export const degreePrograms = [
  {
    id: 1,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree ",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 2,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree ",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 3,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree ",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 4,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  }, 
  {
    id: 5,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree ",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 6,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree ",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 7,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree ",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 8,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 9,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree ",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 10,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree ",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 11,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree ",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
  {
    id: 12,
    courseLink: "https://www.google.com",
    uniLogo: "/images/harverd.webp",
    uniLogoAlt: "university logo",
    uniName: "harverd university",
    courseCat: "Degree",
    courseCatBtnClass: "course-btn course-btn-gray",
    courseTitle: "Harvard: CS50's Introduction to Computer Science",
    courseModuleIcon: "/images/course_certificate.svg",
    courseModuleIconAlt: "Inteinteractive learning",
    courseModule: "International certificate",
    courseDurationIcon: "/images/duration_weeks.svg",
    courseDurationIconAlt: "Duration", 
    courseDuration: "36 months",
    coursePriceIcon: "/images/$currency.svg",
    coursePrice: "$104,000",
    courseTermIcon: "/images/course_term.svg",
    courseTermIconAlt: "Course Term",
    courseTerm: "100% Online",
    sponserdPlatform: "/images/course-box-edx2.png",
    sponserdPlatformAlt: "sponserd platform",
    sponserdByLogo: "/images/logoBlk.png",
    sponserdByLogoAlt: "sponserd by image",
    cornerIcon: "/images/course-box-blackA.png",
    cornerIconAlt: "icon",
    cornerIconLink: "https:www.google.com",
    cornerIconTitle: "view full course",
  },
 
];
