export const educationPrograms = [
    {
      id: 1,
      courseLink: "https://www.yahoo.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course ",
      courseCatBtnClass: "course-btn ",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
       sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: 'images/list-A.webp',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },
    {
      id: 2,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course",
      courseCatBtnClass: "course-btn ",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
      sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: '/images/course-box-blackA.png',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },

    {
      id: 3,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course",
      courseCatBtnClass: "course-btn",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
      sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: '/images/course-box-blackA.png',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },
    {
      id: 4,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course",
      courseCatBtnClass: "course-btn",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
      sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: '/images/course-box-blackA.png',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },
    {
      id: 5,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course ",
      courseCatBtnClass: "course-btn ",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
       sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: 'images/list-A.webp',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },
    {
      id: 6,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course",
      courseCatBtnClass: "course-btn ",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
      sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: '/images/course-box-blackA.png',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },

    {
      id: 7,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course",
      courseCatBtnClass: "course-btn",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
      sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: '/images/course-box-blackA.png',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },
    {
      id: 8,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course",
      courseCatBtnClass: "course-btn",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
      sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: '/images/course-box-blackA.png',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },
    {
      id: 9,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course ",
      courseCatBtnClass: "course-btn ",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
       sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: 'images/list-A.webp',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },
    {
      id: 10,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course",
      courseCatBtnClass: "course-btn ",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
      sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: '/images/course-box-blackA.png',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },

    {
      id: 11,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course",
      courseCatBtnClass: "course-btn",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
      sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: '/images/course-box-blackA.png',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },
    {
      id: 12,
      courseLink: "https://www.google.com",
      uniLogo: '/images/harverd.webp', uniLogoAlt: "university logo",
      uniName: "harverd university",
      courseCat: "Executive course",
      courseCatBtnClass: "course-btn",
      courseTitle: "Harvard: CS50's Introduction to Computer Science",
      courseModuleIcon: "/images/int_learning.svg",
      courseModuleIconAlt: "Inteinteractive learning",
      courseModule: "Fully interactive learning",
      courseDurationIcon: "/images/duration_weeks.svg",
      courseDurationIconAlt: "Duration",      
      courseDuration: "4 weeks",
      courseContentIcon: "/images/graph_bar.svg",
      courseContentIconAlt: "Eligibility",
      courseContent: "Intermediate",
      courseDateIcon: "/images/calendar.svg",
      courseDateIconAlt: "Start Date",
      courseDate: "01 Jan 25",
      sponserdPlatform: "/images/course-box-edx2.png", sponserdPlatformAlt: "sponserd platform",
      sponserdByLogo: '/images/logoBlk.png', sponserdByLogoAlt: "sponserd by image",
      cornerIcon: '/images/course-box-blackA.png',cornerIconAlt: "icon", cornerIconLink: "https:www.google.com", cornerIconTitle: "view full course",
    },
  ];
  